dist: xenial
language: python
python:
  - "2.7"
  - "3.7"

install: pip install pipenv && pipenv install --dev
# command to run tests, e.g. python setup.py test
script:  pipenv run green -r
after_success:
  - bash <(curl -s https://codecov.io/bash)
